using FoodStreetApp.CMS.Interfaces;
using FoodStreetApp.Shared.Context;
using FoodStreetApp.CMS.Services;
using Microsoft.EntityFrameworkCore;
using Npgsql;
using Microsoft.AspNetCore.Components.Authorization;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.HttpOverrides;
using System.Text.Json;
using System.IdentityModel.Tokens.Jwt;
using System.Security.Claims;
using System.Text;
using Microsoft.IdentityModel.Tokens;

var builder = WebApplication.CreateBuilder(args);

// Fix status 134 on Render/Linux by disabling file system watchers
builder.Configuration.AddEnvironmentVariables();

// Configure Port & Protocol at builder stage
var port = int.Parse(Environment.GetEnvironmentVariable("PORT") ?? "10000");
builder.WebHost.ConfigureKestrel(options => {
    options.ListenAnyIP(port, listenOptions => {
        listenOptions.Protocols = Microsoft.AspNetCore.Server.Kestrel.Core.HttpProtocols.Http1;
    });
});
Console.WriteLine($"[STARTUP] Kestrel listening on Port {port} (Any IP, HTTP/1.1 only)");

var connectionString = builder.Configuration.GetConnectionString("Postgres");
var databaseUrl = Environment.GetEnvironmentVariable("DATABASE_URL");

if (!string.IsNullOrWhiteSpace(databaseUrl))
{
    var databaseUri = new Uri(databaseUrl);
    var userInfo = databaseUri.UserInfo.Split(':', 2);

    var npgsqlBuilder = new NpgsqlConnectionStringBuilder
    {
        Host = databaseUri.Host,
        Port = databaseUri.Port,
        Database = databaseUri.AbsolutePath.TrimStart('/'),
        Username = userInfo[0],
        Password = userInfo.Length > 1 ? userInfo[1] : string.Empty,
        SslMode = SslMode.Require
    };

    connectionString = npgsqlBuilder.ConnectionString;
}

builder.Services.AddRazorPages();
builder.Services.AddServerSideBlazor();
builder.Services.AddDbContext<CmsDbContext>(options => 
    options.UseNpgsql(connectionString, x => x.MigrationsAssembly("FoodStreetApp.CMS")));

// Register Gemini translation service
builder.Services.AddHttpClient<IGeminiTranslationService, GeminiTranslationService>()
    .ConfigurePrimaryHttpMessageHandler(() => new HttpClientHandler
    {
        ServerCertificateCustomValidationCallback = (message, cert, chain, errors) => true
    });

// Register Admin Services
builder.Services.AddScoped<IAdminDataService, AdminDataService>();
builder.Services.AddScoped<IQRCodeService, QRCodeService>();
builder.Services.AddScoped<ToastService>();

// Register HttpClient for internal/external API calls
builder.Services.AddScoped(sp => new HttpClient
{
    BaseAddress = new Uri("https://vinh-khanh-food-street-app.onrender.com/")
});

// Auth Services - Switching to JWT
builder.Services.AddScoped<CustomAuthStateProvider>();
builder.Services.AddScoped<AuthenticationStateProvider>(s => s.GetRequiredService<CustomAuthStateProvider>());
builder.Services.AddAuthorizationCore(options =>
{
    options.AddPolicy("AdminOnly", policy => policy.RequireRole("Admin"));
    options.AddPolicy("OwnerOnly", policy => policy.RequireRole("Owner"));
});

var app = builder.Build();

// Configure Forwarded Headers for Render Proxy transparency
app.UseForwardedHeaders(new ForwardedHeadersOptions
{
    ForwardedHeaders = ForwardedHeaders.XForwardedFor | ForwardedHeaders.XForwardedProto
});

// Global Request Logger
app.Use(async (context, next) =>
{
    if (context.Request.Path.StartsWithSegments("/api"))
    {
        Console.WriteLine($"[API-REQUEST] {context.Request.Method} {context.Request.Path}");
    }
    await next();
});

app.MapGet("/health", () => "OK");

// Background Database Synchronization & Initialization
_ = Task.Run(async () => {
    try {
        using var scope = app.Services.CreateScope();
        var dbContext = scope.ServiceProvider.GetRequiredService<CmsDbContext>();
        Console.WriteLine("[DB-Background] Ensuring database created...");
        await dbContext.Database.EnsureCreatedAsync();
        
        string sqlInit = @"
            CREATE TABLE IF NOT EXISTS ""PoiSyncActions"" (
                ""Id"" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                ""PoiId"" integer NOT NULL,
                ""Action"" character varying(20) NOT NULL,
                ""OccurredAtUtc"" timestamp with time zone NOT NULL
            );
            CREATE INDEX IF NOT EXISTS ""IX_PoiSyncActions_OccurredAtUtc"" ON ""PoiSyncActions"" (""OccurredAtUtc"");
            CREATE INDEX IF NOT EXISTS ""IX_PoiSyncActions_PoiId"" ON ""PoiSyncActions"" (""PoiId"");

            ALTER TABLE ""Pois"" ADD COLUMN IF NOT EXISTS ""ImageUrl"" text;
            ALTER TABLE ""UserHistories"" ADD COLUMN IF NOT EXISTS ""DurationSeconds"" integer;
            ALTER TABLE ""UserHistories"" ADD COLUMN IF NOT EXISTS ""QRCode"" text;
        ";
        
        await dbContext.Database.ExecuteSqlRawAsync(sqlInit);

        // Explicit Admin Seeding
        var hasAdmin = await dbContext.Users.AnyAsync(u => u.Username == "admin");
        if (!hasAdmin)
        {
            Console.WriteLine("[DB-Background] Seeding admin user...");
            var adminPasswordHash = BCrypt.Net.BCrypt.HashPassword("123456");
            await dbContext.Database.ExecuteSqlRawAsync(
                "INSERT INTO \"Users\" (\"Id\", \"Username\", \"PasswordHash\", \"Role\") VALUES ({0}, {1}, {2}, {3})",
                Guid.NewGuid(), "admin", adminPasswordHash, "Admin"
            );
            Console.WriteLine("[DB-Background] Admin user seeded successfully.");
        }
    }
    catch (Exception ex) {
        Console.WriteLine($"[DB Error] Background startup sync failed: {ex.Message}");
    }
});

// ==========================================
// API ENDPOINTS (Mapped directly in CMS)
// ==========================================

// 1. AUTH LOGIN
app.MapPost("/api/auth/login", async (JsonElement body, CmsDbContext db, IConfiguration cfg) =>
{
    try
    {
        string? username = body.GetProperty("username").GetString();
        string? password = body.GetProperty("password").GetString();

        if (string.IsNullOrEmpty(username) || string.IsNullOrEmpty(password))
            return Results.BadRequest(new { message = "Username and password are required" });

        Console.WriteLine($"[AUTH] Login attempt for: {username}");

        // Hardcoded debug login
        if (string.Equals(username, "admin", StringComparison.OrdinalIgnoreCase) && password == "123456")
        {
            var adminUser = await db.Users.FirstOrDefaultAsync(u => u.Username == "admin");
            return Results.Ok(new { 
                token = GenerateToken(adminUser?.Id.ToString() ?? Guid.Empty.ToString(), "admin", "Admin", cfg), 
                role = "Admin", 
                username = "admin" 
            });
        }
        if (string.Equals(username, "owner", StringComparison.OrdinalIgnoreCase) && password == "123456")
        {
            var ownerUser = await db.Users.FirstOrDefaultAsync(u => u.Username == "owner");
            return Results.Ok(new { 
                token = GenerateToken(ownerUser?.Id.ToString() ?? Guid.Empty.ToString(), "owner", "Owner", cfg), 
                role = "Owner", 
                username = "owner" 
            });
        }

        var user = await db.Users.FirstOrDefaultAsync(u => u.Username.ToLower() == username.ToLower());
        if (user != null && !string.IsNullOrEmpty(user.PasswordHash))
        {
            if (BCrypt.Net.BCrypt.Verify(password, user.PasswordHash))
            {
                // Normalize role string to Capitalized for the frontend
                var normalizedRole = user.Role;
                if (string.Equals(normalizedRole, "admin", StringComparison.OrdinalIgnoreCase)) normalizedRole = "Admin";
                if (string.Equals(normalizedRole, "owner", StringComparison.OrdinalIgnoreCase)) normalizedRole = "Owner";

                return Results.Ok(new { 
                    token = GenerateToken(user.Id.ToString(), user.Username, normalizedRole, cfg), 
                    role = normalizedRole, 
                    username = user.Username 
                });
            }
        }

        return Results.Unauthorized();
    }
    catch (Exception ex)
    {
        Console.WriteLine($"[AUTH-ERROR] {ex.Message}");
        return Results.Problem("Internal server error during login");
    }
});

string GenerateToken(string userId, string username, string role, IConfiguration cfg)
{
    var jwtSettings = cfg.GetSection("Jwt");
    var key = Encoding.ASCII.GetBytes(jwtSettings["Key"]!);
    var tokenHandler = new JwtSecurityTokenHandler();
    var tokenDescriptor = new SecurityTokenDescriptor
    {
        Subject = new ClaimsIdentity(new[]
        {
            new Claim("userId", userId),
            new Claim("unique_name", username),
            new Claim(ClaimTypes.Name, username),
            new Claim(ClaimTypes.Role, role),
            new Claim("role", role)
        }),
        Expires = DateTime.UtcNow.AddDays(7),
        Issuer = jwtSettings["Issuer"],
        Audience = jwtSettings["Audience"],
        SigningCredentials = new SigningCredentials(new SymmetricSecurityKey(key), SecurityAlgorithms.HmacSha256Signature)
    };
    var token = tokenHandler.CreateToken(tokenDescriptor);
    return tokenHandler.WriteToken(token);
}


// 2. POI & DATA ENDPOINTS
app.MapGet("/api/POI", (IAdminDataService service) => Results.Ok(service.GetPois()));
app.MapGet("/api/POI/{id:int}", (int id, IAdminDataService service) => {
    var item = service.GetPoiById(id);
    return item is null ? Results.NotFound() : Results.Ok(item);
});
app.MapPost("/api/POI", (FoodStreetApp.Shared.Entities.POI poi, IAdminDataService service) => {
    var created = service.AddPoi(poi);
    return Results.Created($"/api/POI/{created.Id}", created);
});

app.MapGet("/api/Audio", (IAdminDataService service) => Results.Ok(service.GetAudios()));
app.MapGet("/api/Tour", (IAdminDataService service) => Results.Ok(service.GetTours()));

// ... remaining mappings can be added as needed or rely on existing services

if (!app.Environment.IsDevelopment())
{
    app.UseExceptionHandler("/Error");
}

app.UseStaticFiles();
app.UseRouting();
app.UseAuthorization();

app.MapBlazorHub();
app.MapFallbackToPage("/_Host");

app.Run();
