BEGIN;

CREATE TABLE IF NOT EXISTS "Pois" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Name" text NOT NULL,
    "Description" text NULL,
    "AudioUrl" text NULL,
    "Latitude" double precision NOT NULL,
    "Longitude" double precision NOT NULL,
    "RadiusMeters" integer NOT NULL DEFAULT 15,
    "IsActive" boolean NOT NULL DEFAULT true,
    "Type" integer NOT NULL DEFAULT 1
);

CREATE TABLE IF NOT EXISTS "Audios" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "PoiId" integer NOT NULL,
    "Title" text NOT NULL,
    "Url" text NOT NULL,
    "DurationSeconds" integer NOT NULL,
    "IsActive" boolean NOT NULL DEFAULT true,
    CONSTRAINT "FK_Audios_Pois_PoiId" FOREIGN KEY ("PoiId") REFERENCES "Pois"("Id") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "Tours" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Name" text NOT NULL,
    "Description" text NULL,
    "IsActive" boolean NOT NULL DEFAULT true,
    "PoiIds" text NOT NULL DEFAULT '[]'
);

CREATE TABLE IF NOT EXISTS "Translations" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "EntityName" text NOT NULL,
    "EntityId" integer NOT NULL,
    "Language" integer NOT NULL DEFAULT 1,
    "FieldName" text NOT NULL,
    "Value" text NOT NULL
);

CREATE TABLE IF NOT EXISTS "UserHistories" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "UserId" text NOT NULL,
    "PoiId" integer NOT NULL,
    "VisitedAtUtc" timestamp with time zone NOT NULL DEFAULT NOW(),
    "Action" text NULL,
    CONSTRAINT "FK_UserHistories_Pois_PoiId" FOREIGN KEY ("PoiId") REFERENCES "Pois"("Id") ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS "IX_Audios_PoiId" ON "Audios" ("PoiId");
CREATE INDEX IF NOT EXISTS "IX_UserHistories_PoiId" ON "UserHistories" ("PoiId");
CREATE INDEX IF NOT EXISTS "IX_Translations_EntityName_EntityId_Language" ON "Translations" ("EntityName", "EntityId", "Language");

COMMIT;
